### ISSUE TITLE
Webhooks not working

### ISSUE THREAD

**Issue by BOHEUS** [twentyhq/twenty#7751]
Reproducible on main after pulling newest changes

**Scenario:** 
1. Log in
2. Go to Settings and toggle "Advanced settings"
3. Go to API & Webhooks
4. Add new webhook or use existing one
5. Check details of the webhook

**Actual:** After adding a webhook or checking details of existing one, errors are thrown in UI, no errors in console in devtools or in logs, when records are added/updated/deleted, no webhook is sent to provided URL
![image](https://github.com/user-attachments/assets/841c967c-3ccb-4dc2-94b0-a492e4ac0127)

**Expected:** No errors must be thrown in UI and webhooks must be sent to provided URL after triggering a specific action (creating/updating/deleting record)

**Comment by martmull** [comment]
@anamarn I think this i related to https://github.com/twentyhq/twenty/pull/7487/files
The token should come from an env variable i guess
![image](https://github.com/user-attachments/assets/60f2860f-2423-4790-b2dc-51dda2520d88)

**Comment by anamarn** [comment]
@BOHEUS i'm working on this issue it should be solved in a PR that would be merged today (#7720). The hardcoded token will be eliminated and replaced with a JWT in a future PR, I will link it here when the PR is opened :).

**Comment by BOHEUS** [comment]
@martmull as far as I know, I haven't started `worker` service as I only ran `npx nx start` command like always, in Local setup docs there is no mention of starting the `worker` service, that's why I reported this issue, could you please write down the `worker` command? I'll check if it's really the case and report back

**Comment by martmull** [comment]
@BOHEUS No problem at all, this is a very common oversight. Here is the command to start the worker
`yarn nx run twenty-server:worker`

**Comment by ehconitin** [comment]
@BOHEUS
`npx nx run twenty-server:worker`

**Comment by BOHEUS** [comment]
@martmull now it works, webhooks are sent to provided URL and like you wrote, `update` events are not working but the error in UI still persists. Did someone delete this command from `npx nx start twenty-server`? It's my first time running different command for launching webhooks feature and I don't recall this workaround from earlier

**Comment by martmull** [comment]
Mmh, maybe before you were using the "sync" queueDriver, that one did not need worker to run. What is your current queueDriver? Check MESSAGE_QUEUE_TYPE env var

**Comment by martmull** [comment]
weird, however I am adding the worker start to the `npx nx start` command -> https://github.com/twentyhq/twenty/pull/7820

**Comment by ehconitin** [comment]
@BOHEUS mine is pg-boss :)
@martmull What is the correct/recommended MESSAGE_QUEUE_TYPE env var?

**Comment by martmull** [comment]
I use pg-boss 🤗

**Comment by ehconitin** [comment]
closed in #7720
